#!/bin/bash

#LOCATIONS
# Data this is where the finished and encrypted files live
# When keys are regenerated this folder will be emptyied 
# default /opt/encore/data

datadir="/opt/encore/data"

# JSON This is where plan text key indexs will live
# these are generated along side the keys
# default /opt/encore/indexs

jsondir="/opt/encore/indexs"

# KEY These are the random encryption keys 
# 128 bit strings for use with the encrypt script
# https://www.fastsitephp.com/fr/documents/file-encryption-bash
# default /opt/encore/keys

keydir="/opt/encore/keys"

# SYSTEM KEY JSON file that contain location and key information 
# are encrypted using this key
# if this key is missing on script call all file in:
# $datadir
# default /opt/encore/keys/systemkey.dk

systemkey="/opt/encore/keys/systemkey.dk"

#log dir

logdir="/opt/encore/logs/log"

# key_max the limit of keys to generate
# default=100
key_max=30

# debugging setting keygen counter
# 0  
# CHANGING THIS WILL BREAK STUFF
key_cur=0

# soft moving
# set 1 to use cp instead of mv when gatheing files to encrypt
# default = 0

soft_move=0

# re-place file
# the original path of files are stored when encrypted
# if set files will be re placed back in there original
# directory
# default=1

re_place=0

# save on destroy
# if you want the destroy function to recover the file before deleting
# the encrypted copy set this to 1
# default=0

leave_in_peace=1