#!/bin/bash
ls -d /mnt/import/* > /etc/store/ls.txt

if [ -s /etc/store/ls.txt ]; then

for file in `cat /etc/store/ls.txt`; do
store "$file" "$( echo "$file" | sed 's_/mnt/import/__g')" dump;
done
rm /etc/store/ls.txt

else

# file empty
exit 0

fi
