#!/bin/bash

source /opt/encore/config

function show_help {
    echo "Help your self foo"
}

if [[ "$1" == "write" ]]; then

elif [[ "$1" == "read" ]]; then

elif [[ "$1" == "destroy" ]]; then

else 
   show_help
   exit 0
fi