#!/bin/bash
source /opt/encore/scripts/functions.sh
source /opt/encore/scripts/debug.sh

function show_help {
    echo "Help your self foo"
    echo -e "# encore [write] [read] [destroy] [initialize]"
    echo -e "[update] [version] \n"
    echo -e "# encore write FILE name owner \n"
    echo -e "# encore read name owner \n"
    echo -e "# encore destroy name owner \n"
    echo -e "# encore initialize **WARNING THIS WILL DELETE ANY STORED DATA AND KEYS** \n"
    echo -e "# encore  backup *Not implemented yet*"
    if [[ "$version" == "V1.50" ]]; then
        echo -e "# encore update just performs a wellness test"
    else  
        echo -e "# encore update performs system wellness test then downloads the lates version of encore"
    fi 
}


if [[ "$1" == "write" ]]; then

    file="$(realpath $2)"
    shortname="$3"
    class="$4"

    if [[ -z "$file" ]]; then
        echo -e "No file given \n"
        exit 1
    fi

    if [[ -z "$shortname" ]]; then
        echo -e "No shortname given \n"
        exit 1
    fi

    if [[ -z "$class" ]]; then
        echo -e "No class given \n"
        exit 1
    fi

    fwrite "$file" "$shortname" "$class"

elif [[ "$1" == "read" ]]; then

    shortname="$2"
    class="$3"
    
    if [[ -z "$shortname" ]]; then
        echo -e "No shortname given \n"
        exit 1
    fi

    if [[ -z "$class" ]]; then
        echo -e "No class given \n"
        exit 1
    fi

    fread "$shortname" "$class"

elif [[ "$1" == "destroy" ]]; then

    shortname="$2"
    class="$3"

    if [[ -z "$shortname" ]]; then
        echo -e "No shortname given \n"  
        exit 1
    fi

    if [[ -z "$class" ]]; then
        echo -e "No class given \n"
        exit 1
    fi

    destroy "$shortname" "$class"

elif [[ "$1" == "initialize" ]]; then

    initialize
    exit 0

elif [[ "$1" == "debug" ]]; then

    if [[ "$2" == "json" ]]; then
    
    shortname="$3"
    class="$4"
    
    debug_json "$shortname" "$class"

    elif [[ -z "$3" ]]; then
        echo -e "morecode \n"
        exit 0
    else
        echo -e "Dont know where to start do you ? \n"
        exit 0
    fi

elif [[ "$1" == "update" ]]; then

    rm -v /opt/encore/install.sh
    wget --no-cache --no-cookies -O /opt/encore/install.sh https://raw.githubusercontent.com/Dj-Codeman/encryption-core/master/install.sh
    bash /opt/encore/install.sh "$2"

elif [[ "$1" == "version" ]]; then
    echo "$version"

else

    show_help
    echo "$version"
    exit 0

fi