#!/bin/bash
version="V1.00"

source /opt/encore/scripts/functions.sh
source /opt/encore/scripts/debug.sh

function show_help {
    echo "Help your self foo"
}


if [[ "$1" == "write" ]]; then

    file="$(realpath $2)"
    shortname="$3"
    class="$4"

    if [[ -z "$file" ]]; then
    echo "No file given"
    exit 0
    fi

    if [[ -z "$shortname" ]]; then
    echo "No shortname given"
    exit 0
    fi

    if [[ -z "$class" ]]; then
    echo "No class given"
    exit 0
    fi

    fwrite "$file" "$shortname" "$class"

elif [[ "$1" == "read" ]]; then

    shortname="$2"
    class="$3"
    
    if [[ -z "$shortname" ]]; then
    echo "No shortname given"
    exit 0
    fi

    if [[ -z "$class" ]]; then
    echo "No class given"
    exit 0
    fi

    fread "$shortname" "$class"

elif [[ "$1" == "destroy" ]]; then

    shortname="$2"
    class="$3"

    if [[ -z "$shortname" ]]; then
    echo "No shortname given"
    exit 0
    fi

    if [[ -z "$class" ]]; then
    echo "No class given"
    exit 0
    fi

    destroy "$shortname" "$class"

elif [[ "$1" == "initialize" ]]; then

    initialize
    exit 0

elif [[ "$1" == "debug" ]]; then

    if [[ "$2" == "json" ]]; then
    
    shortname="$3"
    class="$4"
    
    debug_json "$shortname" "$class"

    elif [[ -z "$3" ]]; then
    echo "morecode"
    else
    echo "Dont know where to start do you ?"
    fi

else 
    show_help
    echo "$version"
    exit 0
fi